#pragma once

#define CHUNK_UPDATE 1

#define CHUNK_LOAD_DISTANCE 4

#define CHUNK_UNLOAD_DISTANCE 6

#define MAX_LOADED_CHUNK ((CHUNK_UNLOAD_DISTANCE * 2) * (CHUNK_UNLOAD_DISTANCE * 2))

#define UNIT_PER_TILE 16

#define UNIT_PER_CHUNK (UNIT_PER_TILE * TILE_PER_CHUNK)

#define TILE_PER_CHUNK 16